version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://medintel:medintel_pass@postgres:5432/medintel_db
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=MEDINTEL_DOCKER_SECRET_KEY_998877
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: ../../docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=medintel
      - POSTGRES_PASSWORD=medintel_pass
      - POSTGRES_DB=medintel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  postgres_data:
